mail.server.host=localhost
mail.server.port=25
mail.server.protocol=smtp
mail.server.username=iatsoftware
mail.server.password=ytND42_)f
mail.server.user-personal=IAT Software
mail.server.user-address=iatsoftware@iatsoftware.net
mail.images.logo-classpath-location=classpath:email/images/logo.png
mail.images.header-classpath-location=classpath:email/images/header.png