# change this
mail.server.host=your-host

#change if necessary
mail.server.port=465
mail.server.protocol=smtp

#change these 
mail.server.username=your-user
mail.server.password=your-password 

mail.server.user-personal=IAT Software

#may leave. sends to localhost so dkim signatures are not an issue
mail.server.user-address=iatsoftware@iatsoftware.net


mail.images.logo-classpath-location=classpath:email/images/logo.png
mail.images.header-classpath-location=classpath:email/images/header.png