iat.webapp.datasource.url=jdbc:mysql://localhost:3306/iatserver_db
iat.webapp.datasource.password=vze4bcmipjiQfOwm
iat.webapp.datasource.user=iat
iat.webapp.datasource.database-name=iatserver_db
iat.webapp.datasource.character-encoding=utf8
