datasource.jdbc-url=jdbc:mysql://localhost:3306/iatserver_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
datasource.username=iat
datasource.password=vze4bcmipjiQfOwm
datasource.driver-class-name=com.mysql.cj.jdbc.Driver